module.exports = {
  port: process.env.PORT,
  app_host:process.env.APP_HOST,
  db_host: process.env.DB_HOST,
  db_user: process.env.DB_USER,
  db_pass: process.env.DB_PASS,
  db_name: process.env.DB_NAME,
  db_port: process.env.DB_PORT,
  sms_url: process.env.SMS_URL,
  sms_user: process.env.SMS_USER,
  sms_pass: process.env.SMS_PASS,
  sms_num: process.env.SMS_NUM,
  sms_otp_pattern: process.env.SMS_OTP_PATTERN,
  sms_verify_pattern: process.env.SMS_VERIFY_PATTERN,
  neshan_api: process.env.NESHAN_API,
  proxy_host:process.env.PROXY_HOST,
  proxy_port: process.env.PROXY_PORT,
  proxy_user: process.env.PROXY_USER,
  proxy_pass: process.env.PROXY_PASS
}